### ISSUE TITLE
Can kubean support kube component file type parameters?

### ISSUE THREAD

**Issue by wawa0210** [kubean-io/kubean#1055]
**usage issue**

kubespray supports setting advanced parameters of kube components by passing in file directories and files.

such as
https://github.com/maciejaszek/kubespray/blob/ffa285c2e798c9cbda8aa5a360fcc068b940c58e/roles/kubernetes/control-plane/tasks/main.yml#L9

```
- import_tasks: pre-upgrade.yml
  tags:
    - k8s-pre-upgrade

- name: Create webhook token auth config
  template:
    src: webhook-token-auth-config.yaml.j2
    dest: "{{ kube_config_dir }}/webhook-token-auth-config.yaml"
    mode: 0640
  when: kube_webhook_token_auth|default(false)

```
If it is kubean, how should it be handled?

Maybe we can define some configmaps and then mount them to kubean jobs for use?
