### ISSUE TITLE
Proposal: Support Ansible Vault Encryption for Host Configuration Security

### ISSUE THREAD

**Issue by ErikJiang** [kubean-io/kubean#1573]
## Summary

Currently, kubean requires storing passwords in plaintext within the host configuration ConfigMap when using username/password authentication. This poses a significant security risk as ConfigMaps are stored unencrypted in etcd and can be easily viewed by anyone with cluster access.

This proposal suggests implementing support for Ansible Vault encryption to secure sensitive information in host configurations, particularly passwords and other authentication credentials.

### Current Security Issues

1. **Plaintext Password Storage**: Passwords are stored in clear text in ConfigMaps:
   ```yaml
   all:
     hosts:
       node1:
         ansible_password: "sensitive_password"  # Stored in plaintext
   ```

2. **Easy Access**: Anyone with kubectl access can view sensitive credentials:
   ```bash
   kubectl get configmap sample-hosts-conf -o yaml
   ```

3. **Audit Trail**: Sensitive information may appear in logs, backups, and audit trails

4. **Compliance**: May violate security compliance requirements for password storage

### Security Risk Assessment

- **Impact**: High - Credential exposure can lead to infrastructure compromise
- **Likelihood**: Medium - Common in multi-user Kubernetes environments
- **Risk Level**: **Critical**

## Proposed Solution

Implement Ansible Vault encryption support for host configuration files, leveraging Ansible's native encryption capabilities.

### Architecture Overview

```
User creates hosts.yml → ansible-vault encrypt → Encrypted ConfigMap → kubean Job (with vault password) → Ansible decrypts automatically
```

### Key Components

1. **Extended CRD Schema**: Add vault password reference and encryption flag
2. **Controller Enhancement**: Support vault password mounting and environment setup
3. **Job Template Updates**: Include vault password file mounting
4. **User Tools**: Helper scripts for encryption workflow

### 1. CRD Schema Extension

```yaml
apiVersion: kubean.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hostsConfRef:
    namespace: kubean-system
    name: sample-hosts-conf
  # New fields for vault support
  vaultPasswordRef:  # Reference to vault password secret
    namespace: kubean-system
    name: sample-vault-password
  encryptionEnabled: true  # Enable/disable encryption
```

### 2. Encrypted ConfigMap Structure

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-hosts-conf
  namespace: kubean-system
  annotations:
    kubean.io/encrypted: "true"  # Encryption marker
data:
  hosts.yml: |
    $ANSIBLE_VAULT;1.1;AES256
    66633366373537643064336432646534653565343834656533653834643862323930633362646234
    6464666266626337643737386264356362316437646364330a623161623834626361316133393037
    ...
```

### 3. Vault Password Secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-vault-password
  namespace: kubean-system
type: Opaque
data:
  vault-password: <base64-encoded-password>
```

#### Controller Changes (`pkg/controllers/clusterops/controller.go`)

- Add vault password mounting logic to job creation
- Set `ANSIBLE_VAULT_PASSWORD_FILE` environment variable
- Handle encrypted content detection and validation

#### Entrypoint Template Updates (`pkg/util/entrypoint/entrypoint.sh.template`)

- Add vault password file detection
- Verify decryption capability before execution
- Set appropriate environment variables for Ansible

### 5. User Workflow

```bash
# 1. Generate vault password
echo "secure-vault-password-2023" > vault-password.txt

# 2. Create hosts file with sensitive data
cat > hosts.yml << EOF
all:
  hosts:
    node1:
      ansible_password: "super_secret_password"
EOF

# 3. Encrypt with ansible-vault
ansible-vault encrypt hosts.yml --vault-password-file vault-password.txt

# 4. Create Kubernetes resources
kubectl create secret generic sample-vault-password \
  --from-file=vault-password=vault-password.txt

kubectl create configmap sample-hosts-conf \
  --from-file=hosts.yml=hosts.yml

# 5. Deploy cluster with encryption enabled
kubectl apply -f cluster.yaml
```

## Benefits

1. **Enhanced Security**: Passwords encrypted at rest using industry-standard AES256
2. **Native Integration**: Leverages Ansible's built-in vault mechanism
3. **Backward Compatibility**: Maintains support for existing plaintext configurations
4. **Minimal Complexity**: Uses existing Ansible tooling and patterns
5. **Compliance**: Meets security requirements for credential storage

### Phase 1: Core Implementation (2-3 weeks)
- [ ] Extend CRD schema for vault support
- [ ] Update controller logic for vault password handling
- [ ] Modify job creation to mount vault password
- [ ] Update entrypoint template for vault detection

### Phase 2: User Experience (1-2 weeks)
- [ ] Create helper scripts for encryption workflow
- [ ] Add comprehensive documentation
- [ ] Create example configurations

### Phase 3: Testing & Validation (1-2 weeks)
- [ ] Unit tests for vault functionality
- [ ] Integration tests with encrypted configurations
- [ ] Security validation and penetration testing
- [ ] Performance impact assessment

### Phase 4: Documentation & Migration (1 week)
- [ ] Update user documentation
- [ ] Create migration guide from plaintext to encrypted
- [ ] Add troubleshooting guide

## Backward Compatibility

- Existing plaintext configurations continue to work unchanged
- Encryption is opt-in via the `encryptionEnabled` flag
- Automatic detection of encrypted vs plaintext content
- Graceful fallback for non-encrypted configurations

## Security Considerations

1. **Vault Password Management**: Secure storage and rotation of vault passwords
2. **Access Control**: RBAC policies for vault password secrets
3. **Audit Logging**: Track all vault-related operations
4. **Memory Safety**: Ensure decrypted content doesn't leak to logs

## Alternative Solutions Considered

1. **SSH Key Authentication**: Already supported, but doesn't solve password scenarios
2. **External Secret Management**: More complex, requires additional dependencies
3. **Custom Encryption**: Reinventing the wheel, less reliable than Ansible Vault
4. **Kubernetes Secrets**: Still visible to cluster administrators

### Unit Tests
- Vault password mounting logic
- Encrypted content detection
- Environment variable setting

### Integration Tests
- End-to-end workflow with encrypted hosts
- Error handling for invalid vault passwords
- Backward compatibility with plaintext configs

### Security Tests
- Verify encrypted content is never logged
- Test vault password access controls
- Validate encryption strength

## Documentation Requirements

1. **User Guide**: How to encrypt host configurations
2. **Migration Guide**: Moving from plaintext to encrypted
3. **Security Best Practices**: Vault password management
4. **Troubleshooting**: Common encryption issues
5. **API Reference**: New CRD fields and their usage

## Success Criteria

- [ ] Sensitive data encrypted at rest in ConfigMaps
- [ ] Zero impact on existing plaintext workflows
- [ ] Simple user experience for encryption setup
- [ ] Comprehensive documentation and examples
- [ ] Security audit approval
- [ ] Performance impact < 5% overhead

## Questions for Community

1. Should we support multiple vault password files per cluster?
2. What's the preferred approach for vault password rotation?
3. Should we provide automatic migration tooling from plaintext to encrypted?
4. Any specific compliance requirements we should consider?

## Related Issues

- Security enhancement discussions
- User feedback about password management
- Compliance requirements from enterprise users

---

**Assignee**: @ErikJiang (author of the proposal)
**Priority**: High (Security-related)
**Labels**: enhancement, security, proposal
**Milestone**: Next release cycle
