### ISSUE TITLE
[E2E-CI] Cilium Pod in Init:CrashLoopBackOff Due to Permission Denied

### ISSUE THREAD

**Issue by FloatXD** [kubean-io/kubean#1575]
**Describe the version**
version about:
kubean v 0.26.2

**Describe the bug**

![Image](https://github.com/user-attachments/assets/30e54c9b-f6ad-44f9-9023-e3565c6f532a)

**How To Reproduce**
Steps to reproduce the issue:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster1-vars-conf
  namespace: new-kubean-system
data:
  group_vars.yml: |
    # k8s-cluster
    unsafe_show_logs: true
    kube_version: "1.31.6"
    container_manager: containerd
    k8s_image_pull_policy: IfNotPresent
    kube_network_plugin: cilium
    kube_network_plugin_multus: false
    kube_apiserver_port: 6443
    kube_proxy_mode: iptables
    enable_nodelocaldns: false
    etcd_deployment_type: kubeadm
    metrics_server_enabled: true
    auto_renew_certificates: true
    local_path_provisioner_enabled: true
    ntp_enabled: true
    kubeadm_init_timeout: 600s
    calico_kubeconfig_wait_timeout: 600

    kube_service_addresses: 10.88.0.0/16
    kube_pods_subnet: 192.88.128.0/20
    kube_network_node_prefix: 24

    calico_cni_name: calico
    calico_felix_premetheusmetricsenabled: true

    # Download Config
    download_run_once: true
    download_container: false
    download_force_cache: true
    download_localhost: true
```

**Screenshots and log**

![Image](https://github.com/user-attachments/assets/83e82269-d609-4c96-ba5e-7b49fb338e80)
