### ISSUE TITLE
software bug: create a cluster with repo undo playhook on centos7, will fail

### ISSUE THREAD

**Issue by wenting-guo** [kubean-io/kubean#470]
**Describe the version**
version about:
1. kubean: 0.4.2-rc5
2. kubespray
3. kubenetes
4. what CNI and itsversion

**Describe the bug**
 create a cluster with repo undo playhook on centos7 offline vm, will fail.

**How To Reproduce**
create a operation config yaml file as follow:
```
apiVersion: kubean.io/v1alpha1
kind: ClusterOperation
metadata:
  name: cluster1-install-09-55-53
  labels:
    clusterName: cluster1
spec:
  cluster: cluster1
  image: m.daocloud.io/ghcr.io/kubean-io/spray-job:v0.4.2-rc5
  backoffLimit: 0
  actionType: playbook
  action: cluster.yml
  preHook:
    - actionType: playbook
      action: ping.yml

    - actionType: playbook
      action: enable-repo.yml  # 在部署集群前, 先执行 enable-repo 的 playbook, 为每个节点创建指定 url 的源配置
      extraArgs: |
        -e "{repo_list: ['http://172.30.41.62:32000/kubean/redhat/\$releasever/os/\$basearch','http://172.30.41.62:32000/kubean/redhat-iso/\$releasever/os/\$basearch']}"

    - actionType: playbook
      action: disable-firewalld.yml

  postHook:
    - actionType: playbook
      action: kubeconfig.yml
    - actionType: playbook
      action: cluster-info.yml
    - actionType: playbook
      action: enable-repo.yml  # 在部署集群前, 先执行 enable-repo 的 playbook, 为每个节点创建指定 url 的源配置
      extraArgs: |
        -e undo=true
```

**Screenshots and log**

TASK [Checking if "/etc/yum.repos.d.bak" exists] *******************************
ok: [node1]
ok: [node2]
Tuesday 17 January 2023  02:11:39 +0000 (0:00:00.907)       0:00:03.926 *******

TASK [Restore "/etc/yum.repos.d" repo] *****************************************
changed: [node2]
changed: [node1]
Tuesday 17 January 2023  02:11:41 +0000 (0:00:01.225)       0:00:05.151 *******
Tuesday 17 January 2023  02:11:41 +0000 (0:00:00.092)       0:00:05.244 *******
Tuesday 17 January 2023  02:11:41 +0000 (0:00:00.117)       0:00:05.361 *******

TASK [Restore apt repositories] ************************************************
fatal: [node1]: FAILED! => {"msg": "The conditional check 'list_file.stat.exists and list_path.stat.exists' failed. The error was: error while evaluating conditional (list_file.stat.exists and list_path.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/kubespray/enable-repo.yml': line 144, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Restore apt repositories\n      ^ here\n"}
fatal: [node2]: FAILED! => {"msg": "The conditional check 'list_file.stat.exists and list_path.stat.exists' failed. The error was: error while evaluating conditional (list_file.stat.exists and list_path.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/kubespray/enable-repo.yml': line 144, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Restore apt repositories\n      ^ here\n"}
